// <auto-generated />
using System;
using Cliente.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cliente.Infra.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20240413194531_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cliente.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e5bdf14-3489-4cfd-bfad-16ab05a8e57c"),
                            BirthDate = new DateTime(1993, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CPF = "00011122233",
                            Email = "nicollas@teste",
                            Name = "Nicollas",
                            Observation = "observação teste",
                            Sex = "Masculino",
                            Telephone = "999998888"
                        },
                        new
                        {
                            Id = new Guid("f2d932ff-2d45-48b0-86b8-a0fa4621c555"),
                            BirthDate = new DateTime(1993, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CPF = "11111122233",
                            Email = "natalia@teste",
                            Name = "Natalia",
                            Observation = "observação teste",
                            Sex = "Feminino",
                            Telephone = "999998888"
                        },
                        new
                        {
                            Id = new Guid("9ebf8d85-532c-4152-87b7-2e8049e521ca"),
                            BirthDate = new DateTime(1993, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CPF = "22211122233",
                            Email = "bento@teste",
                            Name = "Bento",
                            Observation = "observação teste",
                            Sex = "Masculino",
                            Telephone = "999998888"
                        },
                        new
                        {
                            Id = new Guid("6b35c42b-89f6-4a76-b2f6-68aaf9231527"),
                            BirthDate = new DateTime(1993, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CPF = "33311122233",
                            Email = "cecilia@teste",
                            Name = "Cecilia",
                            Observation = "observação teste",
                            Sex = "Feminino",
                            Telephone = "999998888"
                        },
                        new
                        {
                            Id = new Guid("ff1f357d-0175-4e01-8394-154037b28db0"),
                            BirthDate = new DateTime(1993, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CPF = "44411122233",
                            Email = "jose@teste",
                            Name = "Jose",
                            Observation = "observação teste",
                            Sex = "Masculino",
                            Telephone = "999998888"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
